version: '3.7'

services:
  bot:
    build: ./
    volumes:
      - .:/wallet_bot/
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

volumes:
  postgres_data:
